import 'dotenv/config'
import { PrismaPg } from '@prisma/adapter-pg'
import bcrypt from 'bcryptjs'
import { PrismaClient } from '@prisma/client'
import { Pool } from 'pg'

const databaseUrl = process.env.DATABASE_URL

if (!databaseUrl) {
  throw new Error('DATABASE_URL is required for seed')
}

const pool = new Pool({ connectionString: databaseUrl })
const adapter = new PrismaPg(pool)
const prisma = new PrismaClient({ adapter })
const fallbackProductImage = 'https://picsum.photos/seed/kursach-product/600/800'

function buildSizeStock(sizes: string[], totalStock: number) {
  if (sizes.length === 0) {
    return {}
  }

  const base = Math.floor(totalStock / sizes.length)
  const remainder = totalStock % sizes.length

  return Object.fromEntries(
    sizes.map((size, index) => [size, base + (index < remainder ? 1 : 0)]),
  )
}

async function main() {
  const roles = [
    { code: 'ADMIN', name: 'Администратор' },
    { code: 'OPERATOR', name: 'Оператор' },
    { code: 'MANAGER', name: 'Руководитель' },
    { code: 'CLIENT', name: 'Клиент' },
  ]

  for (const role of roles) {
    await prisma.role.upsert({
      where: { code: role.code },
      update: { name: role.name },
      create: role,
    })
  }

  const permissions = [
    { code: 'USERS_MANAGE', resource: 'users', action: 'manage' },
    { code: 'ORDERS_CREATE', resource: 'orders', action: 'create' },
    { code: 'ORDERS_READ', resource: 'orders', action: 'read' },
    { code: 'ORDERS_UPDATE_STATUS', resource: 'orders', action: 'update_status' },
    { code: 'AUDIT_READ', resource: 'audit', action: 'read' },
    { code: 'AI_FORECAST', resource: 'ai', action: 'forecast' },
  ]

  for (const permission of permissions) {
    await prisma.permission.upsert({
      where: { code: permission.code },
      update: permission,
      create: permission,
    })
  }

  const statusData = [
    { code: 'NEW', name: 'Новый', sortOrder: 1 },
    { code: 'IN_PROGRESS', name: 'В работе', sortOrder: 2 },
    { code: 'APPROVED', name: 'Подтвержден', sortOrder: 3 },
    { code: 'REJECTED', name: 'Отклонен', sortOrder: 4 },
    { code: 'CLOSED', name: 'Закрыт', sortOrder: 5 },
  ]

  for (const status of statusData) {
    await prisma.status.upsert({
      where: { code: status.code },
      update: status,
      create: status,
    })
  }

  const adminRole = await prisma.role.findUniqueOrThrow({ where: { code: 'ADMIN' } })
  const adminEmail = process.env.ADMIN_EMAIL ?? 'admin@example.com'
  const adminPassword = process.env.ADMIN_PASSWORD ?? 'Admin123'
  const passwordHash = await bcrypt.hash(adminPassword, 10)

  await prisma.user.upsert({
    where: { email: adminEmail },
    update: { passwordHash, roleId: adminRole.id, status: 'ACTIVE' },
    create: {
      fullName: 'System Admin',
      email: adminEmail,
      passwordHash,
      roleId: adminRole.id,
      status: 'ACTIVE',
    },
  })

  const catalogProducts = [
    {
      sku: 'KRS-OW-0001',
      name: 'Пальто из шерсти с поясом',
      description: 'Теплое пальто прямого кроя с поясом, на подкладке. Подходит для прохладной осени и зимы.',
      image: 'https://images.unsplash.com/photo-1521223890158-f9f7c3d5d504?w=600&h=800&fit=crop',
      price: '12990.00',
      oldPrice: '15990.00',
      isSale: true,
      isNew: false,
      sizes: ['S', 'M', 'L'],
      color: 'beige',
      material: 'wool',
      gender: 'female',
      season: 'winter',
      brand: 'brand1',
      stock: 16,
      category: 'Верхняя одежда',
    },
    {
      sku: 'KRS-SH-0001',
      name: 'Хлопковая рубашка оверсайз',
      description: 'Свободная рубашка из 100% хлопка для повседневных образов.',
      image: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=600&h=800&fit=crop',
      price: '4990.00',
      oldPrice: null,
      isSale: false,
      isNew: true,
      sizes: ['XS', 'S', 'M', 'L'],
      color: 'white',
      material: 'cotton',
      gender: 'female',
      season: 'spring',
      brand: 'brand2',
      stock: 24,
      category: 'Рубашки',
    },
    {
      sku: 'KRS-JN-0001',
      name: 'Джинсы прямого кроя',
      description: 'Классические джинсы прямого силуэта из плотного денима.',
      image: 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=600&h=800&fit=crop',
      price: '6490.00',
      oldPrice: null,
      isSale: false,
      isNew: false,
      sizes: ['28', '30', '32', '34'],
      color: 'blue',
      material: 'denim',
      gender: 'unisex',
      season: 'demi',
      brand: 'brand3',
      stock: 18,
      category: 'Джинсы',
    },
    {
      sku: 'KRS-KW-0001',
      name: 'Кашемировый свитер',
      description: 'Мягкий свитер из кашемира с круглой горловиной.',
      image: 'https://images.unsplash.com/photo-1434389677669-e08b4cda3a20?w=600&h=800&fit=crop',
      price: '8990.00',
      oldPrice: '10990.00',
      isSale: true,
      isNew: false,
      sizes: ['S', 'M', 'L', 'XL'],
      color: 'gray',
      material: 'cashmere',
      gender: 'male',
      season: 'winter',
      brand: 'brand1',
      stock: 12,
      category: 'Трикотаж',
    },
    {
      sku: 'KRS-PT-0001',
      name: 'Льняные брюки широкие',
      description: 'Легкие льняные брюки свободного кроя для теплой погоды.',
      image: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=600&h=800&fit=crop',
      price: '5490.00',
      oldPrice: null,
      isSale: false,
      isNew: true,
      sizes: ['S', 'M', 'L'],
      color: 'beige',
      material: 'linen',
      gender: 'female',
      season: 'summer',
      brand: 'brand4',
      stock: 21,
      category: 'Брюки',
    },
    {
      sku: 'KRS-TS-0001',
      name: 'Базовая футболка хлопок',
      description: 'Базовая футболка из плотного хлопка с аккуратной посадкой.',
      image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600&h=800&fit=crop',
      price: '1990.00',
      oldPrice: null,
      isSale: false,
      isNew: false,
      sizes: ['XS', 'S', 'M', 'L', 'XL'],
      color: 'black',
      material: 'cotton',
      gender: 'unisex',
      season: 'summer',
      brand: 'brand5',
      stock: 40,
      category: 'Футболки',
    },
    {
      sku: 'KRS-OW-0002',
      name: 'Куртка-бомбер из нейлона',
      description: 'Легкий бомбер с функциональными карманами и манжетами.',
      image: 'https://images.unsplash.com/photo-1617137968427-85924c800a22?w=600&h=800&fit=crop',
      price: '9990.00',
      oldPrice: null,
      isSale: false,
      isNew: true,
      sizes: ['S', 'M', 'L', 'XL'],
      color: 'navy',
      material: 'nylon',
      gender: 'male',
      season: 'demi',
      brand: 'brand2',
      stock: 10,
      category: 'Верхняя одежда',
    },
    {
      sku: 'KRS-DR-0001',
      name: 'Платье-миди из вискозы',
      description: 'Женственное платье-миди с мягкой фактурой и комфортной посадкой.',
      image: 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=600&h=800&fit=crop',
      price: '7490.00',
      oldPrice: '8990.00',
      isSale: true,
      isNew: false,
      sizes: ['XS', 'S', 'M', 'L'],
      color: 'red',
      material: 'viscose',
      gender: 'female',
      season: 'spring',
      brand: 'brand3',
      stock: 15,
      category: 'Платья',
    },
    {
      sku: 'KRS-KW-0002',
      name: 'Шерстяной кардиган',
      description: 'Кардиган из шерсти мериноса с пуговицами в тон.',
      image: 'https://images.unsplash.com/photo-1485462537746-965f33f7f6a7?w=600&h=800&fit=crop',
      price: '7990.00',
      oldPrice: null,
      isSale: false,
      isNew: false,
      sizes: ['S', 'M', 'L'],
      color: 'brown',
      material: 'wool',
      gender: 'female',
      season: 'autumn',
      brand: 'brand1',
      stock: 14,
      category: 'Трикотаж',
    },
    {
      sku: 'KRS-PT-0002',
      name: 'Классические брюки slim',
      description: 'Классические брюки slim fit для делового и casual-гардероба.',
      image: 'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=600&h=800&fit=crop',
      price: '5990.00',
      oldPrice: null,
      isSale: false,
      isNew: true,
      sizes: ['44', '46', '48', '50'],
      color: 'black',
      material: 'polyester',
      gender: 'male',
      season: 'demi',
      brand: 'brand4',
      stock: 18,
      category: 'Брюки',
    },
    {
      sku: 'KRS-OW-0003',
      name: 'Пуховик удлиненный',
      description: 'Утепленный пуховик с влагозащитной тканью и капюшоном.',
      image: 'https://images.unsplash.com/photo-1521223890158-f9f7c3d5d504?w=600&h=800&fit=crop',
      price: '15990.00',
      oldPrice: '18990.00',
      isSale: true,
      isNew: false,
      sizes: ['M', 'L', 'XL'],
      color: 'green',
      material: 'polyester',
      gender: 'unisex',
      season: 'winter',
      brand: 'brand2',
      stock: 8,
      category: 'Верхняя одежда',
    },
    {
      sku: 'KRS-SK-0001',
      name: 'Юбка плиссе атлас',
      description: 'Плиссированная юбка-миди из атласной ткани.',
      image: 'https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?w=600&h=800&fit=crop',
      price: '4490.00',
      oldPrice: null,
      isSale: false,
      isNew: true,
      sizes: ['XS', 'S', 'M', 'L'],
      color: 'pink',
      material: 'silk',
      gender: 'female',
      season: 'summer',
      brand: 'brand5',
      stock: 17,
      category: 'Юбки',
    },
    {
      sku: 'KRS-AC-0001',
      name: 'Кожаный ремень классический',
      description: 'Универсальный ремень из натуральной кожи с металлической пряжкой.',
      image: 'https://images.unsplash.com/photo-1624222247344-550fb60583dc?w=600&h=800&fit=crop',
      price: '2990.00',
      oldPrice: null,
      isSale: false,
      isNew: true,
      sizes: ['90', '95', '100', '105'],
      color: 'brown',
      material: 'leather',
      gender: 'unisex',
      season: 'demi',
      brand: 'brand3',
      stock: 30,
      category: 'Аксессуары',
    },
    {
      sku: 'KRS-DR-0002',
      name: 'Платье-рубашка хлопковое',
      description: 'Легкое платье-рубашка на пуговицах для повседневных образов.',
      image: 'https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=600&h=800&fit=crop',
      price: '6890.00',
      oldPrice: null,
      isSale: false,
      isNew: true,
      sizes: ['S', 'M', 'L'],
      color: 'white',
      material: 'cotton',
      gender: 'female',
      season: 'summer',
      brand: 'brand2',
      stock: 13,
      category: 'Платья',
    },
    {
      sku: 'KRS-SH-0002',
      name: 'Рубашка фланелевая в клетку',
      description: 'Мягкая фланелевая рубашка прямого кроя.',
      image: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=600&h=800&fit=crop',
      price: '5290.00',
      oldPrice: '6490.00',
      isSale: true,
      isNew: false,
      sizes: ['M', 'L', 'XL'],
      color: 'red',
      material: 'cotton',
      gender: 'male',
      season: 'autumn',
      brand: 'brand1',
      stock: 22,
      category: 'Рубашки',
    },
    {
      sku: 'KRS-TS-0002',
      name: 'Футболка oversize graphic',
      description: 'Свободная футболка с минималистичным принтом.',
      image: 'https://images.unsplash.com/photo-1527719327859-c6ce80353573?w=600&h=800&fit=crop',
      price: '2490.00',
      oldPrice: null,
      isSale: false,
      isNew: true,
      sizes: ['S', 'M', 'L', 'XL'],
      color: 'black',
      material: 'cotton',
      gender: 'unisex',
      season: 'summer',
      brand: 'brand4',
      stock: 35,
      category: 'Футболки',
    },
    {
      sku: 'KRS-JN-0002',
      name: 'Джинсы mom fit',
      description: 'Женские джинсы mom fit с высокой посадкой.',
      image: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=600&h=800&fit=crop',
      price: '6990.00',
      oldPrice: null,
      isSale: false,
      isNew: false,
      sizes: ['26', '27', '28', '29', '30'],
      color: 'blue',
      material: 'denim',
      gender: 'female',
      season: 'demi',
      brand: 'brand5',
      stock: 16,
      category: 'Джинсы',
    },
    {
      sku: 'KRS-PT-0003',
      name: 'Брюки карго',
      description: 'Практичные брюки карго с боковыми карманами.',
      image: 'https://images.unsplash.com/photo-1552902865-b72c031ac5ea?w=600&h=800&fit=crop',
      price: '7590.00',
      oldPrice: '8990.00',
      isSale: true,
      isNew: false,
      sizes: ['S', 'M', 'L', 'XL'],
      color: 'green',
      material: 'cotton',
      gender: 'male',
      season: 'demi',
      brand: 'brand2',
      stock: 19,
      category: 'Брюки',
    },
    {
      sku: 'KRS-KW-0003',
      name: 'Свитшот базовый',
      description: 'Утепленный базовый свитшот для прохладной погоды.',
      image: 'https://images.unsplash.com/photo-1622470953794-aa9c70b0fb9d?w=600&h=800&fit=crop',
      price: '5790.00',
      oldPrice: null,
      isSale: false,
      isNew: true,
      sizes: ['S', 'M', 'L', 'XL'],
      color: 'gray',
      material: 'cotton',
      gender: 'unisex',
      season: 'autumn',
      brand: 'brand3',
      stock: 27,
      category: 'Трикотаж',
    },
    {
      sku: 'KRS-OW-0004',
      name: 'Тренч двубортный',
      description: 'Классический двубортный тренч с поясом.',
      image: 'https://images.unsplash.com/photo-1551232864-3f0890e580d9?w=600&h=800&fit=crop',
      price: '13990.00',
      oldPrice: null,
      isSale: false,
      isNew: false,
      sizes: ['S', 'M', 'L'],
      color: 'beige',
      material: 'polyester',
      gender: 'female',
      season: 'spring',
      brand: 'brand1',
      stock: 9,
      category: 'Верхняя одежда',
    },
    {
      sku: 'KRS-SK-0002',
      name: 'Юбка-карандаш миди',
      description: 'Строгая юбка-карандаш для офиса и повседневного стиля.',
      image: 'https://images.unsplash.com/photo-1582142306909-195724d33ffc?w=600&h=800&fit=crop',
      price: '4890.00',
      oldPrice: null,
      isSale: false,
      isNew: true,
      sizes: ['XS', 'S', 'M', 'L'],
      color: 'black',
      material: 'viscose',
      gender: 'female',
      season: 'demi',
      brand: 'brand4',
      stock: 20,
      category: 'Юбки',
    },
    {
      sku: 'KRS-AC-0002',
      name: 'Шарф шерстяной',
      description: 'Теплый шарф из шерсти с мягкой текстурой.',
      image: 'https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?w=600&h=800&fit=crop',
      price: '3290.00',
      oldPrice: null,
      isSale: false,
      isNew: false,
      sizes: ['ONE'],
      color: 'navy',
      material: 'wool',
      gender: 'unisex',
      season: 'winter',
      brand: 'brand5',
      stock: 26,
      category: 'Аксессуары',
    },
    {
      sku: 'KRS-SH-0003',
      name: 'Льняная рубашка regular',
      description: 'Дышащая рубашка из льна для теплых дней.',
      image: 'https://images.unsplash.com/photo-1603252109303-2751441dd157?w=600&h=800&fit=crop',
      price: '5590.00',
      oldPrice: null,
      isSale: false,
      isNew: true,
      sizes: ['S', 'M', 'L', 'XL'],
      color: 'beige',
      material: 'linen',
      gender: 'male',
      season: 'summer',
      brand: 'brand2',
      stock: 23,
      category: 'Рубашки',
    },
    {
      sku: 'KRS-TS-0003',
      name: 'Поло из пике',
      description: 'Классическое поло из хлопкового пике.',
      image: 'https://images.unsplash.com/photo-1620012253295-c15cc3e65df4?w=600&h=800&fit=crop',
      price: '3990.00',
      oldPrice: '4590.00',
      isSale: true,
      isNew: false,
      sizes: ['M', 'L', 'XL'],
      color: 'white',
      material: 'cotton',
      gender: 'male',
      season: 'summer',
      brand: 'brand1',
      stock: 18,
      category: 'Футболки',
    },
    {
      sku: 'KRS-JN-0003',
      name: 'Джинсы wide leg',
      description: 'Широкие джинсы с комфортной посадкой.',
      image: 'https://images.unsplash.com/photo-1602293589930-45aad59ba3ab?w=600&h=800&fit=crop',
      price: '7290.00',
      oldPrice: null,
      isSale: false,
      isNew: true,
      sizes: ['28', '29', '30', '31', '32'],
      color: 'blue',
      material: 'denim',
      gender: 'unisex',
      season: 'demi',
      brand: 'brand3',
      stock: 21,
      category: 'Джинсы',
    },
    {
      sku: 'KRS-DR-0003',
      name: 'Платье-комбинация',
      description: 'Лаконичное платье-комбинация на тонких бретелях.',
      image: 'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=600&h=800&fit=crop',
      price: '6390.00',
      oldPrice: null,
      isSale: false,
      isNew: true,
      sizes: ['XS', 'S', 'M', 'L'],
      color: 'red',
      material: 'silk',
      gender: 'female',
      season: 'summer',
      brand: 'brand4',
      stock: 14,
      category: 'Платья',
    },
    {
      sku: 'KRS-OW-0005',
      name: 'Парка утепленная',
      description: 'Теплая парка с капюшоном и объемными карманами.',
      image: 'https://images.unsplash.com/photo-1539533113208-f6df8cc8b543?w=600&h=800&fit=crop',
      price: '14990.00',
      oldPrice: '17990.00',
      isSale: true,
      isNew: false,
      sizes: ['M', 'L', 'XL'],
      color: 'green',
      material: 'nylon',
      gender: 'male',
      season: 'winter',
      brand: 'brand2',
      stock: 11,
      category: 'Верхняя одежда',
    },
    {
      sku: 'KRS-KW-0004',
      name: 'Водолазка из мериноса',
      description: 'Тонкая водолазка из шерсти мериноса для базового гардероба.',
      image: 'https://images.unsplash.com/photo-1618886614638-80e3c103d31a?w=600&h=800&fit=crop',
      price: '6790.00',
      oldPrice: null,
      isSale: false,
      isNew: false,
      sizes: ['S', 'M', 'L'],
      color: 'brown',
      material: 'wool',
      gender: 'female',
      season: 'winter',
      brand: 'brand5',
      stock: 16,
      category: 'Трикотаж',
    },
    {
      sku: 'KRS-PT-0004',
      name: 'Брюки джоггеры',
      description: 'Комфортные джоггеры из мягкого футера.',
      image: 'https://images.unsplash.com/photo-1506629905607-d9ce4c0b2f8d?w=600&h=800&fit=crop',
      price: '4690.00',
      oldPrice: null,
      isSale: false,
      isNew: true,
      sizes: ['S', 'M', 'L', 'XL'],
      color: 'gray',
      material: 'cotton',
      gender: 'unisex',
      season: 'autumn',
      brand: 'brand3',
      stock: 29,
      category: 'Брюки',
    },
    {
      sku: 'KRS-AC-0003',
      name: 'Бейсболка хлопковая',
      description: 'Минималистичная бейсболка с регулируемой застежкой.',
      image: 'https://images.unsplash.com/photo-1521369909029-2afed882baee?w=600&h=800&fit=crop',
      price: '2290.00',
      oldPrice: null,
      isSale: false,
      isNew: true,
      sizes: ['ONE'],
      color: 'black',
      material: 'cotton',
      gender: 'unisex',
      season: 'summer',
      brand: 'brand4',
      stock: 33,
      category: 'Аксессуары',
    },
  ]

  const categories = [...new Set(catalogProducts.map((product) => product.category))]
  const categoryIds = new Map<string, number>()

  for (const category of categories) {
    const item = await prisma.category.upsert({
      where: { name: category },
      update: {},
      create: { name: category },
    })

    categoryIds.set(category, item.id)
  }

  await prisma.product.deleteMany()
  await prisma.product.createMany({
    data: catalogProducts.map((product) => ({
      sku: product.sku,
      name: product.name,
      description: product.description,
      image: product.image?.trim() ? product.image : fallbackProductImage,
      price: product.price,
      oldPrice: product.oldPrice,
      isSale: product.isSale,
      isNew: product.isNew,
      sizes: product.sizes,
      sizeStock: buildSizeStock(product.sizes, product.stock),
      color: product.color,
      material: product.material,
      gender: product.gender,
      season: product.season,
      brand: product.brand,
      stock: product.stock,
      categoryId: categoryIds.get(product.category),
    })),
  })

  const promoCodes = [
    {
      code: 'WELCOME10',
      title: 'Скидка 10% на первый заказ',
      description: 'Тестовый промокод для проверки скидки 10%',
      discountType: 'PERCENT' as const,
      discountValue: '10.00',
      minSubtotal: '3000.00',
      maxDiscount: '3000.00',
      usageLimit: 1000,
      perUserLimit: 1,
      isActive: true,
      startsAt: null,
      endsAt: null,
    },
    {
      code: 'FIX500',
      title: 'Скидка 500 ₽',
      description: 'Тестовый фиксированный промокод',
      discountType: 'FIXED' as const,
      discountValue: '500.00',
      minSubtotal: '2000.00',
      maxDiscount: null,
      usageLimit: 1000,
      perUserLimit: 3,
      isActive: true,
      startsAt: null,
      endsAt: null,
    },
  ]

  for (const promo of promoCodes) {
    await prisma.promoCode.upsert({
      where: { code: promo.code },
      update: {
        title: promo.title,
        description: promo.description,
        discountType: promo.discountType,
        discountValue: promo.discountValue,
        minSubtotal: promo.minSubtotal,
        maxDiscount: promo.maxDiscount,
        usageLimit: promo.usageLimit,
        perUserLimit: promo.perUserLimit,
        isActive: promo.isActive,
        startsAt: promo.startsAt,
        endsAt: promo.endsAt,
      },
      create: promo,
    })
  }

  const operatorRole = await prisma.role.findUniqueOrThrow({ where: { code: 'OPERATOR' } })
  const managerRole = await prisma.role.findUniqueOrThrow({ where: { code: 'MANAGER' } })
  const clientRole = await prisma.role.findUniqueOrThrow({ where: { code: 'CLIENT' } })

  const testUsers = [
    {
      fullName: 'Иван Оператор',
      email: 'operator@example.com',
      password: 'Operator123',
      roleId: operatorRole.id,
      status: 'ACTIVE' as const,
    },
    {
      fullName: 'Мария Руководитель',
      email: 'manager@example.com',
      password: 'Manager123',
      roleId: managerRole.id,
      status: 'ACTIVE' as const,
    },
    {
      fullName: 'Петр Клиент',
      email: 'client1@example.com',
      password: 'Client123',
      roleId: clientRole.id,
      status: 'ACTIVE' as const,
    },
    {
      fullName: 'Елена Клиент',
      email: 'client2@example.com',
      password: 'Client123',
      roleId: clientRole.id,
      status: 'ACTIVE' as const,
    },
    {
      fullName: 'Тест Блокировка',
      email: 'blocked@example.com',
      password: 'Blocked123',
      roleId: clientRole.id,
      status: 'BLOCKED' as const,
    },
  ]

  for (const testUser of testUsers) {
    const testPasswordHash = await bcrypt.hash(testUser.password, 10)
    await prisma.user.upsert({
      where: { email: testUser.email },
      update: {
        fullName: testUser.fullName,
        passwordHash: testPasswordHash,
        roleId: testUser.roleId,
        status: testUser.status,
      },
      create: {
        fullName: testUser.fullName,
        email: testUser.email,
        passwordHash: testPasswordHash,
        roleId: testUser.roleId,
        status: testUser.status,
      },
    })
  }
}

main()
  .then(async () => {
    await prisma.$disconnect()
  })
  .catch(async (error) => {
    console.error(error)
    await prisma.$disconnect()
    process.exit(1)
  })